H1 User Competency (Rasch Model)

In [1]:
# # Compare
# test_max = rasch.groupby(['UserID','SatzID']).agg({'Datum':np.max})
# test_max = test_max.reset_index()
# test_max = pd.merge(test_max, rasch, on=['UserID','SatzID','Datum'])
# test_max
# test_min = rasch.groupby(['UserID','SatzID']).agg({'Datum':np.min})
# test_min = test_min.reset_index()
# test_min = pd.merge(test_min, rasch, on=['UserID','SatzID','Datum'])
# test_min

# sns.countplot(data=test_max, x="Erfolg")
# sns.countplot(data=test_min, x="Erfolg")

In [2]:
import pandas as pd
import pickle
from scipy import stats
import numpy as np
import seaborn as sns
import pingouin as pg
import statsmodels.formula.api as s

c:\Python310\lib\site-packages\outdated\utils.py:14: OutdatedPackageWarning: The package outdated is out of date. Your version is 0.2.1, the latest is 0.2.2.
Set the environment variable OUTDATED_IGNORE=1 to disable these warnings.
  return warn(

In [3]:
#import
df = pickle.load(open( '../00_data/cleaned/sitzungssummary.pkl','rb') )
xmlsaetze = pickle.load(open( '../00_data/cleaned/xmlsaetze.pkl','rb') )

xmlsaetze = xmlsaetze[xmlsaetze.Testposition=='pruefung']

rasch = xmlsaetze[['UserID','SatzID','Erfolg','Datum']]

rasch['UserID'].astype(str)
rasch['SatzID'].astype(str)

72826         4082
72829         4091
72970         2703
73085         4083
73087         4098
            ...
4980980        609
4981007    9991753
4981009    9991756
4981012    9991774
4981014    9991753
Name: SatzID, Length: 191246, dtype: object

In [4]:
test = rasch.groupby(['UserID','SatzID']).agg({'Datum':np.min})
test = test.reset_index()
test = pd.merge(test, rasch, on=['UserID','SatzID','Datum'])
test

         UserID   SatzID                Datum  Erfolg
0        186923      873  2022-09-06 10:20:40       1
1        186923      878  2022-09-06 10:21:23       1
2        186923      882  2022-09-06 10:21:13       1
3        186923      891  2022-09-06 10:20:56       1
4        186923  9992530  2022-09-06 10:20:33       1
...         ...      ...                  ...     ...
133585  1064116      661  2022-10-30 21:12:10       1
133586  1064116     2705  2022-10-30 20:58:49       1
133587  1064116     3893  2022-10-30 22:41:58       0
133588  1064116     3902  2022-10-30 22:42:34       1
133589  1064116     3904  2022-10-30 22:30:06       1

[133590 rows x 4 columns]

In [5]:
rasch = test.pivot_table(values='Erfolg', index=test.UserID, columns='SatzID', aggfunc='last')
rasch

SatzID,127,128,129,130,131,132,133,134,135,136,...,9992992,9992993,9992994,9992995,9992996,9992997,9992998,9992999,9993000,9993001
UserID,,,,,,,,,,,,,,,,,,,,,
186923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
360974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
373836,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
409463,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
435839,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1063461,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1063470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1063762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1063918,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1064116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#Subjects with only 1 valid response must be removed

In [7]:
delete_li = []
for col in rasch:
    cnt = rasch[col].count()
    if cnt < 2:
        delete_li.append(col)

In [8]:
rasch = rasch.drop(columns=[378 ,379 ,782 ,2685 ,3905 ,3908 ,3910 ,3923 ,3927 ,3928 ,3937 ,3962 ,3968 ,4073 ,4087 ,4088 ,9991691 ,9991692 ,9991699 ,9991700 ,9991701 ,9991703 ,9991705 ,9991706 ,9991708 ,9991712 ,9991713 ,9991716 ,9991717 ,9991718 ,9991719 ,9991752 ,9991764 ,9991775 ,9991776 ,9991845 ,9991872 ,9991873 ,9991874 ,9991876 ,9991877 ,9991880 ,9991883 ,9991887 ,9991888 ,9991890 ,9991892 ,9991893 ,9991895 ,9991896 ,9991897 ,9991898 ,9991899 ,9991900 ,9992081 ,9992082 ,9992085 ,9992086 ,9992087 ,9992092 ,9992097 ,9992100 ,9992101 ,9992103 ,9992104 ,9992108 ,9992109 ,9992110 ,9992228 ,9992229 ,9992240 ,9992241 ,9992249 ,9992264 ,9992990 ,9992995 ,9993000])

In [9]:
delete_li = []
for index, row in rasch.iterrows():
    cnt = row.count()
    if cnt < 2:
        delete_li.append(index)
        rasch = rasch.drop([index])

rasch

SatzID,127,128,129,130,131,132,133,134,135,136,...,9992989,9992991,9992992,9992993,9992994,9992996,9992997,9992998,9992999,9993001
UserID,,,,,,,,,,,,,,,,,,,,,
186923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
360974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
373836,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
409463,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
435839,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1063461,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1063470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1063762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1063918,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1064116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
rasch.to_csv('learning_data.csv')