In [1]:
import pandas as pd
import pickle

In [2]:
df = pd.read_csv( 'learning_data.csv')
df

,UserID,127,128,129,130,131,132,133,134,135,...,9992989,9992991,9992992,9992993,9992994,9992996,9992997,9992998,9992999,9993001
0,186923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,360974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,373836,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,409463,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,435839,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8086,1063461,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8087,1063470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8088,1063762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8089,1063918,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8090,1064116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# user id as index
df=df.set_index('UserID')
# drop rows with 0 values
df = df.dropna(how='all')
# create index with four digits
df.index = df.index.astype(str).str.pad(7, side='left', fillchar='0')
# change 1.0 to 1
df = df.replace([1.0],'1')
# change 0.0 to 0
df = df.replace([0.0],'0')
# change NaN to .
df = df.fillna('.', inplace=False)

In [4]:
df

,127,128,129,130,131,132,133,134,135,136,...,9992989,9992991,9992992,9992993,9992994,9992996,9992997,9992998,9992999,9993001
UserID,,,,,,,,,,,,,,,,,,,,,
0186923,.,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
0360974,.,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
0373836,.,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
0409463,.,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
0435839,.,.,.,.,.,.,.,.,1,.,...,.,.,.,.,.,.,.,.,.,.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1063461,.,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
1063470,.,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
1063762,.,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
1063918,.,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
1064116,.,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.

In [5]:
df.to_csv('conquest_input_data.csv')

In [6]:
######## Manually
# open as csv in excel
## drop column row 
## row to string -> komma entfernen
## close csv
# open csv in editor
## save as dat